judge_options:
- client_config: {}
  client_type: openai
  judge_model: gpt-4o-mini
  judge_prompt: 'Given a question and the ground truth answer, determine if the response
    is correct. Respond according to the judge response format.


    question={question}

    response={response}

    ground truth answer={answer}

    judge response format={judge_response_format}'
  type: binary
- client_config: {}
  client_type: openai
  judge_model: gpt-4.1-nano
  judge_prompt: 'Given a question and the ground truth answer, determine if the response
    is correct. Respond according to the judge response format.


    question={question}

    response={response}

    ground truth answer={answer}

    judge response format={judge_response_format}'
  response_format:
    type: discrete
    options: [1.0, 2.0, 3.0, 4.0, 5.0]
    meanings:
      1.0: terrible
      2.0: bad
      3.0: fine
      4.0: good
      5.0: great
  type: discrete
name: first_responder
reward_strategy:
  base_weight: 1.0
  level_multiplier: 0.5
  type: levelweighted
